config/routes.rb
SweetNothings::Application.routes.draw do
  resources :nothings

  root :to => 'nothing#index'

end

app/models/nothing.rb
class Nothing < ActiveRecord::Base
  attr_accessible :message
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/nothings_controller.rb
class NothingsController < ApplicationController
  # GET /nothings
  # GET /nothings.json
  def index
    @nothings = Nothing.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @nothings }
    end
  end

  # GET /nothings/1
  # GET /nothings/1.json
  def show
    @nothing = Nothing.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @nothing }
    end
  end

  # GET /nothings/new
  # GET /nothings/new.json
  def new
    @nothing = Nothing.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @nothing }
    end
  end

  # GET /nothings/1/edit
  def edit
    @nothing = Nothing.find(params[:id])
  end

  # POST /nothings
  # POST /nothings.json
  def create
    @nothing = Nothing.new(params[:nothing])

    respond_to do |format|
      if @nothing.save
        format.html { redirect_to @nothing, notice: 'Nothing was successfully created.' }
        format.json { render json: @nothing, status: :created, location: @nothing }
      else
        format.html { render action: "new" }
        format.json { render json: @nothing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /nothings/1
  # PUT /nothings/1.json
  def update
    @nothing = Nothing.find(params[:id])

    respond_to do |format|
      if @nothing.update_attributes(params[:nothing])
        format.html { redirect_to @nothing, notice: 'Nothing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @nothing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nothings/1
  # DELETE /nothings/1.json
  def destroy
    @nothing = Nothing.find(params[:id])
    @nothing.destroy

    respond_to do |format|
      format.html { redirect_to nothings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nothings_helper.rb
module NothingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SweetNothings</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/nothings/_form.html.erb
<%= form_for(@nothing) do |f| %>
  <% if @nothing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@nothing.errors.count, "error") %> prohibited this nothing from being saved:</h2>

      <ul>
      <% @nothing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "whisper something:"%><br />
    <%= f.text_field :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/nothings/edit.html.erb
<h1>Not what you meant in your heart?</h1>

<%= render 'form' %>

<%= link_to 'Show', @nothing %> |
<%= link_to 'Back', nothings_path %>

app/views/nothings/index.html.erb
<h1>Sweet nothings</h1>

<table>
  <tr>
    <th>Whisperings</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @nothings.each do |nothing| %>
  <tr>
    <td><%= nothing.message %></td>
    <td><%= link_to 'Show', nothing %></td>
    <td><%= link_to 'Edit', edit_nothing_path(nothing) %></td>
    <td><%= link_to 'Destroy', nothing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Nothing', new_nothing_path %>

app/views/nothings/new.html.erb
<h1>Whisper a sweet new nothing</h1>

<%= render 'form' %>

<%= link_to 'Back', nothings_path %>

app/views/nothings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Ah, thank you:</b>
  <%= @nothing.message %>
</p>


<%= link_to 'Edit', edit_nothing_path(@nothing) %> |
<%= link_to 'Back', nothings_path %>